# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ceef1493fa67a7cdd29d5f97f717c363c745a41cb2552a8d52c1d44d2d4d7e46d0140f1e89969a31e8e8b174ca24de4e19711ff12e096380e394c04b77cb018

test:
  secret_key_base: 7ce8b9082d1f4bf0cc712c11c29dc7e8fdad170905357588d1845cd130e83f2cfb5463bf6dd2d5fd5fb76b28ae34516790ff7751863fed6043bab48be6de14f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
